### ISSUE TITLE
Notify user if the date/time he is adding does not exist

### ISSUE THREAD

**Issue by szenius** [cs2103aug2015-f10-2j/main#4]
So that he can change the date

**Comment by ngzikai** [comment]
Sorry Ashish, I'll reassign this to you instead, I think this feature is better fitted under ArgParser which you are currently working on.

**Comment by zzzikai** [comment]
Sorry Ashish, I'll reassign this to you instead, I think this feature is better fitted under ArgParser which you are currently working on.
